name: Build and Publish .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Use your desired .NET version

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Publish the application
    - name: Publish
      run: dotnet publish -c Release -o ./TextDiff/publish

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        wsl docker build -t gittextdiff .
