name: Build and Publish .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Use your desired .NET version

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Publish the application
    - name: Publish
      run: dotnet publish -c Release -o ./TextDiff/publish

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up unused images
      run: docker image prune -f

    - name: Build Docker image
      run: |
          # Generate unique tags
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME="gitdiff"
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
  
          # Build the image with both unique and 'latest' tags
          docker build --no-cache -f ./TextDiff/Dockerfile -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_HASH -t $IMAGE_NAME:$TIMESTAMP .
